mm_website_project/mm_website_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from seances import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^seances/', include(('seances.urls', 'seances'), namespace='seances')),
    url(r'^thelmaetlouise/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mm_website_project/seances/urls.py
from django.conf.urls import url

from . import views # import views so we can use them in urls.

urlpatterns = [
    url(r'^$', views.listing, name='listing'),
    url(r'^populated(?P<populated>[0-9]+)(?P<seance_id>[0-9]+)/$', views.listing, name='listing2'),
    url(r'^(?P<film_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^content/(?P<value>\d+)/$', views.content, name='content'),
    # url(r'^?Lieu=(?P<value_lieu>\d+)&Date=(?P<value_lieu>\d+)&Film=&query=Valider$', views.populated_listing, name='populated_listing'),
]

mm_website_project/seances/models.py
from django.db import models

class Seance(models.Model):
    date = models.DateField()
    lieu = models.CharField(max_length=200, blank=True, default='')
    animations = models.TextField(max_length=10000, blank=True, default='')
    plein_air = models.BooleanField(default=False)
    festival = models.BooleanField(default=False)
    mois_du_doc = models.BooleanField(default=False)

    def __str__(self):
        msg = "Séance du "+str(self.date)+" ayant lieu à "+str(self.lieu)
        return msg

class Film(models.Model):
    titre = models.CharField(max_length=200, unique=True)
    real = models.CharField(max_length=200, blank=True, default='')
    acteurs = models.CharField(max_length=200, blank=True, default='')
    genre = models.CharField(max_length=200, blank=True, default='')
    annee = models.SmallIntegerField(blank=True, null=True)
    duree = models.SmallIntegerField(blank=True, null=True)
    pays = models.CharField(max_length=200, default='')
    age = models.SmallIntegerField(blank=True, null=True)
    synopsis = models.TextField(max_length=10000, blank=True, default='')
    photo = models.ImageField(blank=True, null=True)
    page_allocine = models.URLField(blank=True, default='')

    def __str__(self):
        return self.titre

class Projection(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    seance = models.ForeignKey(Seance, on_delete=models.CASCADE)
    heure = models.TimeField()
    animation = models.TextField(max_length=10000, blank=True, default='')
    tarif = models.FloatField(blank=True, null=True)
    tarif_reduit = models.FloatField(blank=True, null=True, verbose_name='Tarif réduit')

    def __str__(self):
        msg = "Projection de "+str(self.film)+" à "+str(self.seance.lieu)+" le "+str(self.seance.date)+" à "+str(self.heure)
        return msg

class CarouselSlider(models.Model):
    image = models.ImageField(blank=True, null=True)  # the pic used as slider
    date_d_ajout = models.DateField(auto_now=True, verbose_name='Date d\'ajout')
    nom = models.CharField(max_length=200, blank=True, default='')

    class Meta:
        verbose_name = 'Images de carrousel'
#    def __str__(self):
#        return self.titre

#    def save(self, *args, **kwars):  # changing the save method so there can only be one
        # Catalogue object with home_page == True (so only one Catalogue will be presented
        # on the home page)
#        if self.home_page == True:
#            try:
#                temp = Catalogue.objects.get(home_page=True)
#                if self != temp:
#                    temp.home_page = False
#                    temp.save()
#            except Catalogue.DoesNotExist:
#                pass
#            super(Catalogue, self).save(*args, **kwars)
#        else:
#            super(Catalogue, self).save(*args, **kwars)

mm_website_project/seances/forms.py
from django import forms
from .models import Film, Seance, Projection

class FormSeances(forms.Form):  #  this form is used to filter the seances on the
    #   appropriate page.
    location_dict = [('','------')]  #the first tuple is the empty choice
    date_dict = [('','------')]
    film_dict = [('','------')]
    for seance in Seance.objects.all():
        if (seance.lieu, seance.lieu) not in location_dict:  # we don't wan't twice or more the same
            # lieu or date or film in the choices
            location_dict.append((seance.lieu, seance.lieu))
        if (seance.date, seance.date) not in date_dict:
            date_dict.append((seance.date, seance.date))
    for film in Film.objects.all():
        if (film.titre, film.titre) not in film_dict:
            if len(film.projection_set.all()) != 0:
                film_dict.append((film.titre, film.titre))
    location_dict.sort()
    try:  # 'try' is needed since empty date field raises a TypeError
        date_dict.sort()
    except:
        pass
    film_dict.sort()
    Lieu = forms.ChoiceField(choices=location_dict, required=False)
    Date = forms.ChoiceField(choices=date_dict, required=False)
    Film = forms.ChoiceField(choices=film_dict, required=False)

class NlForm(forms.Form):  # this form is used to register new emails to the newsletter
    email = forms.EmailField(required=True, label="Votre adresse mail")

class ScrapyForm(forms.Form):
    film_url = forms.URLField(help_text="Indiquer ici l'url de la page allociné du film")

mm_website_project/seances/views.py
from django.shortcuts import render, get_object_or_404, redirect
import datetime
import pytz
from django.core.paginator import Paginator
from .models import Film, Seance, Projection, CarouselSlider
from .forms import FormSeances

def home(request):
    seances = []  # une liste de séances vide
    today = datetime.date.today()  # ici et dessous on compare si la séance est passée ou pas
    for seance in Seance.objects.all().order_by('date'):
        if seance.date >= today:
            seances.append(seance)  # si séance pas passée, on l'ajoute à la liste
    paginator = Paginator(seances, 6)  # pour ne présenter que 6 séances max sur la page d'accueil
    page_obj = paginator.page(request.GET.get('page', '1'))
    context = {
        'seances' : seances,
        'page_obj' : page_obj,
    }
    return render(request, 'seances/home.html', context)

def listing(request, populated=0, seance_id=None): #  this view returns all the screenings in the dbase + research form
    for elt in Seance.objects.all():
        #  comparing seance's date (converted into an aware datetime.datetime object,
        #  with 23h59 set as time so the seance disapears only the day after)
        #  with timezone aware datetime.datetime."now" object, set on UTC+2 (Paris)
        if datetime.datetime(elt.date.year, elt.date.month, elt.date.day, 23, 59,
                             tzinfo=pytz.timezone('Europe/Paris')) < pytz.utc.localize(datetime.datetime.utcnow()).astimezone(pytz.timezone('Europe/Paris')):
            elt.delete()
    query = request.GET.get('query')
    if populated == '1':  # populated == 1 when a seance is clicked on, on the home page. It populates the form
        # with this particular seance's date and location.
        query = True
        request.GET = request.GET.copy()
        request.GET['Lieu'] = Seance.objects.get(pk=seance_id).lieu
        request.GET['Date'] = Seance.objects.get(pk=seance_id).date
    if query:
        seances = []
        form = FormSeances(request.GET)
        if form.is_valid():
            lieu = str(form.cleaned_data['Lieu'])  #getting the data form the form, converting it in str
            date = str(form.cleaned_data['Date'])
            film = str(form.cleaned_data['Film'])
            if lieu and date and film:  # i did not find a better way of coding this filter mechanism
                seances = Seance.objects.filter(lieu=lieu,
                                                date=date,
                                                projection__film__titre=film).order_by('date')
            if lieu and date and not film:  # 2
                seances = Seance.objects.filter(lieu=lieu, date=date).order_by('date')
            if lieu and film and not date:  # 2
                seances = Seance.objects.filter(lieu=lieu, projection__film__titre=film).order_by('date')
            if date and film and not lieu:  # 2
                seances = Seance.objects.filter(date=date, projection__film__titre=film).order_by('date')
            if date and not film and not lieu:
                seances = Seance.objects.filter(date=date).order_by('date')
            if film and not date and not lieu:
                seances = Seance.objects.filter(projection__film__titre=film).order_by('date')
            if lieu and not film and not date:
                seances = Seance.objects.filter(lieu=lieu).order_by('date')
            if len(seances) == 0:
                message = "Désolé, il n'existe aucune séance correspondant à ces critères !"
            else:
                message = ""
            form = FormSeances()
            context = {
                'seances' : seances,
                'message' : message,
                'form' : form,
            }
            return render(request, 'seances/listing.html', context)
        else:
            form = FormSeances()
            seances = Seance.objects.all().order_by('date')
            film = Film.objects.all().order_by('titre')
            context = {
                'seances': seances,
                'film': film,
                'form': form,
            }
            return render(request, 'seances/listing.html', context)
    else:
        form = FormSeances()
        seances = Seance.objects.all().order_by('date')
        film = Film.objects.all().order_by('titre')
        context = {
        'seances' : seances,
        'film' : film,
        'form' : form,
    }
        return render(request, 'seances/listing.html', context)

def detail(request, film_id):  #  this view shows every parameters a particular screening has
    film = get_object_or_404(Film, pk=film_id)
    projections = film.projection_set.all().order_by('seance__date')
    context = {
        'film': film,
        'projections': projections,
    }
    return render(request, 'seances/detail.html', context)

def content(request, value):
    if int(value) == 0:
        return render(request, 'seances/content/asso.html')
    elif int(value) == 1:
        return render(request, 'seances/content/equipe.html')
    elif int(value) == 2:
        return render(request, 'seances/content/conseil.html')
    elif int(value) == 3:
        return render(request, 'seances/content/partenaires.html')
    elif int(value) == 4:
        return render(request, 'seances/content/contact.html')
    # this page below is not active, there is no content yet on it
    elif int(value) == 5:
        return render(request, 'seances/content/emploi.html')
    elif int(value) == 6:
        return render(request, 'seances/content/rejoindre.html')
    elif int(value) == 7:
        return render(request, 'seances/content/education.html')
    elif int(value) == 8:
        return render(request, 'seances/content/louise.html')
    elif int(value) == 9:
        return render(request, 'seances/content/ecole-college.html')
    elif int(value) == 10:
        return render(request, 'seances/content/mater.html')
    elif int(value) == 11:
        return render(request, 'seances/content/ecole.html')
    elif int(value) == 12:
        return render(request, 'seances/content/college65.html')
    elif int(value) == 13:
        return render(request, 'seances/content/louise.html')
    elif int(value) == 14:
        return render(request, 'seances/content/scolaires.html')
    elif int(value) == 15:
        return render(request, 'seances/content/ecole-college.html')
    elif int(value) == 16:
        return render(request, 'seances/content/lyceens-apprentis.html')
    elif int(value) == 17:
        return render(request, 'seances/content/festival.html')
    elif int(value) == 18:
        return render(request, 'seances/content/college43.html')

mm_website_project/seances/templates/seances/base.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" shrink-to-fit=no">

    <title>Mondes et Multitudes - Cinéma itinérant et ateliers d'éducation aux images en Aveyron</title>

    {% load static %}

    <!-- Bootstrap Core CSS added directly from their site on the 19/04/2021, page : https://getbootstrap.com/docs/4.1/getting-started/introduction/ -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- developer's own modifications -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/developers.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">


</head>

<body>

<div class="brand-and-adress-bar">
    <div class="brand"><a href="{% url 'home' %}">Mondes et Multitudes</a></div>
    <div class="address-bar">Cinéma itinérant et ateliers d'éducation aux images en Aveyron</div>
</div>

<!-- copied from OCR beginning -->

<nav class="navbar navbar-expand-lg navbar-light">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
    <div id="navbarNavDropdown" class="collapse navbar-collapse">
        <ul class="navbar-nav container-fluid justify-content-around align-items-center">
            <li class="nav-item">
                <a href="{% url 'home' %}">Accueil</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'seances:listing' %}">Séances</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'seances:content' value=6 %}">Organiser une séance</a>
            </li>
            <li class="nav-item dropdown size-limit-1">
                <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Éducation aux images
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'seances:content' value=7 %}">Présentation générale</a><br>
                    <a class="dropdown-item" href="{% url 'seances:content' value=8 %}">Les ateliers de Louise</a><br>
                    <a class="dropdown-item" href="{% url 'seances:content' value=9 %}">Les dispositifs scolaires</a>
                </div>
            </li>
            <li class="nav-item size-limit-2">
                <a href="{% url 'seances:content' value=17 %}">Festival Ouvre l'Oeil</a>
            </li>
            <li class="nav-item dropdown size-limit-3">
                <a class="nav-link" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Qui sommes-nous ?
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                  <a class="dropdown-item" href="{% url 'seances:content' value=0 %}">L'association</a><br>
                  <a class="dropdown-item" href="{% url 'seances:content' value=1 %}">L'équipe</a><br>
                  <a class="dropdown-item" href="{% url 'seances:content' value=2 %}">Le conseil d'administration</a>
                  <!-- this link is deactivated until they give me some content
                  <br>
                  <a class="dropdown-item" href="">Nos partenaires</a>
                  -->
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Contact
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
                  <a class="dropdown-item" href="{% url 'seances:content' value=4 %}">Nous contacter</a>
                  <!-- this link is deactivated until they give me some content
                  <br>
                  <a class="dropdown-item" href="">Offres d'emploi</a>
                  -->
                </div>
            </li>
        </ul> <!-- navbar unordered list container -->
    </div>
</nav>
<!-- copied from OCR end -->

<!-- a container to place social media buttons above the carousel -->
<div class="socialmedia-and-carousel-container">
    <div class="socialmedia-block-container">
        <div class="socialmedia-icon-container">
            <a href="https://www.facebook.com/mondesetmultitudes" title="Rejoignez-nous sur Facebook !">
                <img class="socialmedia-icon" src="{% static 'img/pepouze.png' %}">
            </a>
        </div>
        <div class="socialmedia-icon-container newsletter">
            <a href="" data-toggle="modal" data-target="#exampleModal" title="Inscrivez-vous à notre newsletter">
                <img class="socialmedia-icon" src="{% static 'img/pepouze2.png' %}">
            </a>
        </div>
    </div>

<!-- Modal for the newsletter registration -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Inscription à la newsletter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form action="" method="POST" id="nlform">
            {% csrf_token %}
            {{ nl_form }}
          </form>
      </div>
      <div class="modal-footer">
        <button form= "nlform" type="button" class="btn btn-secondary" data-dismiss="modal">Quitter</button>
        <button form="nlform" type="submit" class="btn btn-primary" name="query">Valider</button>
      </div>
        <p class="mentions_form">Informations personnelles et vie privée : voir les <a href="{% url 'seances:content' value=4 %}">mentions légales ici.</a></p>
    </div>
  </div>
</div>

<!-- beginning of carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
      {% for slide, bool in carousel_sliders_dict.items %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"{% if bool %} class="active"{% endif %}></li>
      {% endfor %}
  </ol>
  <div class="carousel-inner">
      {% for slide, bool in carousel_sliders_dict.items %}
    <div class="carousel-item{% if bool %} active{% endif %}">
      <img class="d-block w-100" src="{{ slide.image.url }}" alt="Slide">
    </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- end of carousel -->

</div> <!-- the container for social media and carousel -->

<!-- beginning of the page -->
        <div class="container-fluid">
      <div class="row">
        <div class="box container-fluid">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
<!-- end of the page -->

<footer>
    <p class="mentions-legales-footer">
        Association Mondes et Multitudes <br>
        7 Route du Moulin, Saint-Cyprien-sur-Dourdou <br>
        12320 – Conques en Rouergue <br>
        Du lundi au vendredi : 9h-13h/14h-17h <br>
        09 53 79 93 01 <br>
        mondesetmultitudes@gmail.com <br>
        <a href="{% url 'seances:content' value=4 %}">Mentions légales</a>
    </p>
</footer>


<!-- Bootstrap JS added directly from their site on the 19/04/2021, page : https://getbootstrap.com/docs/4.1/getting-started/introduction/ -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

mm_website_project/seances/templates/seances/detail.html
{% extends 'seances/base.html' %}
{% load static %}
{% block content %}
<hr>
    <h1 class="intro-text text-center">{{ film.titre }}</h1>
<hr class="detail-separator">
<div class="container-fluid">
    <div class="row seance-listing">
        <div class="col-12 col-md-4">
            {% if film.photo %}
            <img src="{{ film.photo.url }}" alt="{{ film.titre }}" class="img-listing">
            {% endif %}
        </div>
        <div class="card col-12 col-md-8 bg-transparent">
            <div class="card-body">
                {% if film.real %} <h3 class="card-title"> De {{ film.real }}</h3> {% endif %}
                <div class="not-justified-card-presentation">
                    <p class="card-text bold-card-presentation not-justified-card-presentation">
                        {% if film.acteurs %} Avec {{ film.acteurs }} {% endif %} <br>
                        {% if film.genre %} {{ film.genre }},{% endif %}
                        {% if film.annee %} {{ film.annee }},{% endif %}
                        {% if film.pays %} {{ film.pays }},{% endif %}
                        {% if film.duree %} {{ film.duree }} minutes {% endif %} <br>
                        {% if film.age %} À partir de {{ film.age }} ans {% endif %} <br>
                    </p>
                </div>
                <p class="card-text">
                    {% if film.synopsis %} {{ film.synopsis }} {% endif %}
                </p>
                <p>
                    <span class="bold-card-presentation">
                        Séances de ce film :<br>
                    </span>
                </p>
                <ul>
                    {% for projection in projections %}
                        <li><span class="seance-bold">le {{ projection.seance.date }} à {{ projection.seance.lieu }} {{ projection.heure }}. Tarif : {% if projection.tarif %} {{ projection.tarif }} {% endif %} € {% if projection.tarif_reduit %}; Tarif réduit : {{ projection.tarif_reduit }} € {% endif %} </span><br>
                    {% if projection.seance.plein_air %}
                        <img src="{% static 'img/macaron_plein_air_NOIR_AVEC_TEXTE.png' %}" alt="Séance en plein air" title="Séance en plein air" class="macaron">
                    {% endif %}
                    {% if projection.seance.festival %}
                        <img src="{% static 'img/macaron_ouvre_l_oeil_NOIR_AVEC_TEXTE.png' %}" alt="Séance du festival Ouvre l'Œil" title="Séance du festival Ouvre l'Œil" class="macaron">
                    {% endif %}
                        {% if projection.seance.mois_du_doc %}
                        <img src="{% static 'img/macaron_mois_du_doc_NOIR_AVEC_TEXTE.png' %}" alt="Séance du festival Mois du doc" title="Séance du festival Mois du doc" class="macaron">
                    {% endif %}
                        </li>
                        <br>
                    {% endfor %}
                </ul>
            </div> <!-- card-body -->
        </div> <!-- card -->
    </div> <!-- row -->
</div> <!-- container-fluid -->




{% endblock %}

mm_website_project/seances/templates/seances/home.html
<!-- cette page affiche les 5 prochaines séances TODO mettre un bouton de lien vers toutes les séances à venir -->
 {% extends 'seances/base.html' %}

 {% block content %}
<div class="col-12">
    <hr>
    <h2 class="intro-text text-center">Les prochaines séances
    </h2>
    <hr class="detail-separator">
</div>

<div class="row">
{% for seance in page_obj %}
        <div class="col-12 col-md-2 card text-center bg-transparent" style="width: 18rem;">
            <!-- below we only get the first photo on the proj list of the seance -->
            <a class="link_populated_home_page" href="{% url 'seances:listing2' populated=1 seance_id=seance.id %}">
                {% if seance.projection_set.all.0.film.photo %}
                    <img class="card-img-top imghomepage" src="{{ seance.projection_set.all.0.film.photo.url }}" />
                {% endif %}
                <div class="textdatelieuwrapper">
                    <h3 class="card-title h3datelieu">{{ seance.date }}</h3>
                    <h4 class="card-subtitle h3datelieu h3lieu">{{ seance.lieu }}</h4>
                </div>
            </a>
            <div class="textfilmstitles">
                {% for projection in seance.projection_set.all %}
                    <p class="card-text" id="homecardtext">
                        <a id="home-card-link" href="{% url 'seances:detail' film_id=projection.film.id %}">
                            {{ projection.film.titre }}
                        </a>
                    </p>
                {% endfor %}
            </div>
        </div>
{% endfor %}
</div> <!-- row -->

<div class="col-lg-12">

    <h6>
        <a id="voir_toutes" href="{% url 'seances:listing' %}">
            Voir toutes les séances à venir
        </a>
    </h6>
</div>

{% endblock %}

mm_website_project/seances/templates/seances/listing.html
<!-- page de liste de toutes les séances, passées ou à venir -->
{% extends 'seances/base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">Les séances programmées
    </h2>
    <hr class="detail-separator">
</div>

<p>Recherchez parmis les séances programmées : </p>
<form action="{% url 'seances:listing' %}" method="get">
{{ form.as_p }}
<input type="submit" value="Valider" name="query">
</form>

{# below is the error message if the form returns no results #}
{{ message }}

{# à réactiver plus tard {% include 'seances/search_form.html' %} #}

<div class="container-fluid">
    {% for seance in seances %}
    <div class="row seance-listing">
            <div class="col-12">
                <h2>le {{ seance.date }} à {{ seance.lieu }}</h2>
                    {% if seance.plein_air %}
                    <img src="{% static 'img/macaron_plein_air_NOIR_AVEC_TEXTE.png' %}" alt="Séance en plein air" title="Séance en plein air" class="macaron">
                    {% endif %}
                    {% if seance.festival %}
                    <img src="{% static 'img/macaron_ouvre_l_oeil_NOIR_AVEC_TEXTE.png' %}" alt="Séance du festival Ouvre l'Œil" title="Séance du festival Ouvre l'Œil" class="macaron">
                    {% endif %}
                    {% if seance.mois_du_doc %}
                    <img src="{% static 'img/macaron_mois_du_doc_NOIR_AVEC_TEXTE.png' %}" alt="Séance du festival Mois du doc" title="Séance du festival Mois du doc" class="macaron">
                    {% endif %}
            </div> <!-- end of col-12 -->
    </div> <!-- end of row -->
{% for projection in seance.projection_set.all|dictsort:"heure" %}
    <div class="row seance-listing">
        <div class="col-12 col-md-4">
            {% if projection.film.photo %}
            <img class="img-listing" src="{{ projection.film.photo.url }}" alt="{{ projection.film.titre }}">
            {% endif %}
        </div>
        <div class="card col-12 col-md-8 bg-transparent card-listing-page">
            <div class="card-body">
                <h3 class="card-title">{{ projection.heure }} :
                    <a class="film-title-listing" href="{% url 'seances:detail' film_id=projection.film.id %}">
                        {{ projection.film.titre }}
                    </a>
                </h3>
                <p class="card-text">
                    <span class="bold-card-presentation">
                        {% if projection.film.real %} De {{ projection.film.real }} <br> {% endif %}
                        {% if projection.film.acteurs %} Avec {{ projection.film.acteurs }} <br> {% endif %}
                        {% if projection.film.genre %} {{ projection.film.genre }},{% endif %}
                        {% if projection.film.annee %} {{ projection.film.annee }},{% endif %}
                        {% if projection.film.pays %} {{ projection.film.pays }},{% endif %}
                        {% if projection.film.duree %} {{ projection.film.duree }} minutes <br> {% endif %}
                        {% if projection.film.age %} À partir de {{ projection.film.age }} ans <br> {% endif %}
                    </span>
                    <br>
                    {% if projection.film.synopsis %} {{ projection.film.synopsis }} <br> {% endif %}
                    <br>
                    <span class="bold-card-presentation">
                        {% if projection.animation %} Animation : {{ projection.animation }} <br> {% endif %}
                        {% if projection.tarif %} Tarif :  {{ projection.tarif }} € <br> {% endif %}
                        {% if projection.tarif_reduit %} Tarif réduit :  {{ projection.tarif_reduit }} € <br> {% endif %}
                    </span>
                </p>
            </div> <!-- end of card-body -->
        </div> <!-- end of card -->
    </div> <!-- end of row -->
{% endfor %}

{% endfor %}

</div> <!-- end of container of the page -->
<div class="col-lg-12">

    <h6>
        <a id="voir_toutes" href="{% url 'seances:listing' %}">
            Voir toutes les séances à venir
        </a>
    </h6>
</div>

{% endblock %}